setxkbmap se

# Japanese input
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
exec fcitx -d &

# Transparency
picom --experimental-backends &

# Top bar
dwmblocks &

# Increase keypress freq
xset r rate 200 40 &

# Load xresources
xrdb "$HOME/.config/x11/xresources"

# Keybindings
sxhkd &

# Wallpaper
xwallpaper --zoom /home/axel/.local/share/bg

# Notifications
dunst &

# Window manager
exec dwm

