setxkbmap se

# Japanese input
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
exec fcitx -d &

# matlab jank
export _JAVA_AWT_WM_NONREPARENTING=1

# Transparency
picom --experimental-backends &

# Top bar
dwmblocks &

# Increase keypress freq
xset r rate 200 40 &

# Remap caps to escape
xmodmap -e "clear lock"
xmodmap -e "keycode 66 = Escape NoSymbol Escape"

# Load xresources
xrdb "$HOME/.config/x11/xresources"

# Keybindings
sxhkd &

# Notifications
dunst &

# Window manager
exec dwm

